#!/bin/bash
# DesiTree Deployment Script for desitree.in
# Run this after setting up GitHub, Railway, and Vercel

echo "🚀 DesiTree Deployment to desitree.in"
echo "====================================="
echo ""

# Step 1: GitHub Setup
echo "1️⃣  GitHub Repository Setup:"
echo "   • Go to https://github.com/new"
echo "   • Create repo: 'desitree' (public)"
echo "   • Copy the repo URL"
echo "   • Run these commands:"
echo ""
echo "     cd c:\\Users\\Administrator\\Downloads\\DT"
echo "     git remote add origin https://github.com/YOUR_USERNAME/desitree.git"
echo "     git branch -M main"
echo "     git push -u origin main"
echo ""
read -p "Press Enter after pushing to GitHub..."

# Step 2: Railway Backend Deployment
echo ""
echo "2️⃣  Railway Backend Deployment:"
echo "   • Go to https://railway.app"
echo "   • Sign up/login (free)"
echo "   • Click 'New Project' → 'Deploy from GitHub'"
echo "   • Select your 'desitree' repo"
echo "   • Railway auto-detects Node.js"
echo "   • Go to Variables tab, add:"
echo ""
echo "     NODE_ENV=production"
echo "     MONGO_URI=mongodb+srv://user:pass@cluster.mongodb.net/desitree"
echo "     JWT_SECRET=your_secure_jwt_secret"
echo "     CLOUDINARY_CLOUD_NAME=your_cloud_name"
echo "     CLOUDINARY_API_KEY=your_api_key"
echo "     CLOUDINARY_API_SECRET=your_api_secret"
echo "     GOOGLE_CLIENT_ID=your_google_client_id"
echo "     GOOGLE_CLIENT_SECRET=your_google_client_secret"
echo "     FRONTEND_URL=https://desitree.in"
echo ""
echo "   • Click Deploy"
echo "   • Copy the Railway URL (e.g., https://desitree-backend.railway.app)"
echo ""
read -p "Press Enter after Railway deployment..."

# Step 3: Vercel Frontend Deployment
echo ""
echo "3️⃣  Vercel Frontend Deployment:"
echo "   • Go to https://vercel.com"
echo "   • Sign up/login (free)"
echo "   • Click 'Add New...' → 'Project'"
echo "   • Import Git Repository → Select 'desitree'"
echo "   • Configure:"
echo "     - Root Directory: client/"
echo "     - Framework Preset: Vite"
echo "     - Build Command: npm run build"
echo "     - Output Directory: dist"
echo "   • Add Environment Variable:"
echo "     - VITE_API_BASE=https://api.desitree.in"
echo "   • Click Deploy"
echo ""
read -p "Press Enter after Vercel deployment..."

# Step 4: Custom Domain Setup
echo ""
echo "4️⃣  Custom Domain Setup:"
echo ""
echo "   Railway (Backend - api.desitree.in):"
echo "   • In Railway dashboard → Your project → Settings → Domains"
echo "   • Click 'Add Domain' → Enter: api.desitree.in"
echo "   • Railway shows DNS records to add"
echo ""
echo "   Vercel (Frontend - desitree.in):"
echo "   • In Vercel dashboard → Your project → Settings → Domains"
echo "   • Click 'Add' → Enter: desitree.in"
echo "   • Also add: www.desitree.in"
echo "   • Vercel shows nameservers to use"
echo ""

# Step 5: DNS Configuration in GoDaddy
echo ""
echo "5️⃣  DNS Configuration in GoDaddy:"
echo "   • Login to GoDaddy account"
echo "   • Go to Domain Settings → DNS Management"
echo "   • Add these records:"
echo ""
echo "     Type: CNAME"
echo "     Name: api"
echo "     Value: cname.railway.app"
echo "     TTL: 1 hour"
echo ""
echo "     Type: NS"
echo "     Name: @"
echo "     Value: ns1.vercel-dns.com"
echo ""
echo "     Type: NS"
echo "     Name: @"
echo "     Value: ns2.vercel-dns.com"
echo ""
echo "     Type: NS"
echo "     Name: @"
echo "     Value: ns3.vercel-dns.com"
echo ""
echo "     Type: NS"
echo "     Name: @"
echo "     Value: ns4.vercel-dns.com"
echo ""
echo "   • Save changes"
echo "   • DNS propagation takes 24-48 hours"
echo ""

# Step 6: Final Environment Updates
echo ""
echo "6️⃣  Final Environment Updates:"
echo ""
echo "   Railway Variables (if needed):"
echo "   • FRONTEND_URL=https://desitree.in"
echo "   • Redeploy after DNS setup"
echo ""
echo "   Vercel Variables:"
echo "   • VITE_API_BASE=https://api.desitree.in"
echo "   • Redeploy if changed"
echo ""

# Step 7: Testing
echo ""
echo "7️⃣  Testing Your Deployment:"
echo ""
echo "   After 24-48 hours, test:"
echo "   • Frontend: https://desitree.in"
echo "   • Backend: https://api.desitree.in"
echo "   • Run: bash check-domain.sh"
echo ""
echo "   If issues:"
echo "   • Check Railway/Vercel logs"
echo "   • Verify DNS with https://whatsmydns.net"
echo "   • Clear browser cache"
echo ""

echo "🎉 Deployment Complete!"
echo ""
echo "Your DesiTree app will be live at:"
echo "🌐 https://desitree.in"
echo "🔗 API: https://api.desitree.in"
echo ""
echo "Questions? Check DEPLOYMENT.md or CUSTOM_DOMAIN.md"
